version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = [
    "nodejs",
    "jest",
    "mongo",
    "browser"
]
dialect = "typescript"
module_system = "es-modules"
plugins = ["react"]
style_guide = "airbnb"
